name: fast-api-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - fastapi=0.128.7=h877c79a_0
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - fastapi-core=0.128.7=pyhcf101f3_0
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py313h5ea7bf4_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libmpdec=4.0.0=hfd05255_1
  - libsqlite=3.51.2=hf5d6505_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_1
  - libxml2-16=2.15.1=h692994f_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py313hd650c13_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.3.0=hac47afa_455
  - numpy=2.4.2=py313hce7ae62_1
  - openssl=3.6.1=hf411b9b_1
  - pandas=3.0.0=py313h26f5e95_0
  - pip=26.0.1=pyh145f28c_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py313hfbe8231_1
  - pydantic-extra-types=2.11.0=pyhcf101f3_1
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.13.12=h09917c8_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-multipart=0.0.22=pyhcf101f3_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pyyaml=6.0.3=py313hd650c13_1
  - rich=14.3.2=pyhcf101f3_0
  - rich-toolkit=0.19.2=pyhcf101f3_0
  - scikit-learn=1.8.0=np2py313h4ce4a18_1
  - setuptools=82.0.0=pyh332efcf_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - starlette=0.52.1=pyhfdc7a7d_0
  - tbb=2022.3.0=h3155e25_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h6ed50ae_3
  - tomli=2.4.0=pyhcf101f3_0
  - typer=0.21.2=pyhf0a747c_0
  - typer-slim=0.21.2=pyhcf101f3_0
  - typer-slim-standard=0.21.2=h0939d6c_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - uvicorn=0.40.0=pyh6dadd2b_0
  - uvicorn-standard=0.40.0=hcfb189c_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - watchfiles=1.1.1=py313hf61f64f_0
  - websockets=16.0=py313h5fd188c_1
  - yaml=0.2.5=h6a83c73_3
  - pip:
    - scipy==1.17.0
prefix: C:\Users\jacqu\anaconda3\envs\fast-api-demo
